# Generated by Django 3.0.4 on 2020-06-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('heading', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Destinations1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('username', models.CharField(max_length=200)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Destinations2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
